### ISSUE TITLE
Sorting donors by total donations throws an error

### ISSUE THREAD

**Issue by Drenmi** [TechLadies/highpoint#108]
When attempting to sort the donors in `DonorsController#index` by total donations, the application breaks.

<img width="1004" alt="screen shot 2016-11-19 at 16 37 00" src="https://cloud.githubusercontent.com/assets/5259935/20454346/20cceaf4-ae79-11e6-99a3-2965b3a3e612.png">

---

This is because this part:

```
if @sort_column == "total_donations"
  if @sort_direction == "ASC"
    @result.sort_by(&:total_donations)
  else
    @result.sort_by(&:total_donations).reverse
  end
else
  ...
```

returns an `Array` instead of an `ActiveRecord::Relation`.

**Comment by limxinyuuu** [comment]
I have applied the fix in pull request #107 😃
