### ISSUE TITLE
Date input field in "Add Event" modal is not formatted correctly

### ISSUE THREAD

**Issue by alahab2** [TechLadies/highpoint#13]
Current formatting of `date_field` is `mm/dd/yyyy`. It's better to change it to `dd/mm/yyyy`.

**Comment by alahab2** [comment]
What do you think about using this gem https://github.com/Nerian/bootstrap-datepicker-rails for date input fields?

**Comment by Drenmi** [comment]
@alahab2: Yes. This is a common library used "in the wild." As long as it works with Bootstrap 4, I'm okay with it. 😀
