### ISSUE TITLE
Link to the donors' show pages from the index page

### ISSUE THREAD

**Issue by Drenmi** [TechLadies/highpoint#21]
The results in the donors index should link to the individual donors' pages.

<img width="828" alt="screen shot 2016-10-10 at 14 46 33" src="https://cloud.githubusercontent.com/assets/5259935/19228553/ea93a760-8ef8-11e6-89ed-89924c167d1d.png">

**Comment by limxinyuuu** [comment]
A link to the individual donors' page has been added to the NRIC/UEN field in the donors index.
