### ISSUE TITLE
Unable to redirect sign in to donations after signing out

### ISSUE THREAD

**Issue by farrahfazirah** [TechLadies/highpoint#35]
After signing out of the HCSA management system, it leads to the sign in page. However when signing in again (only after the user signs out) it does not redirect the user back to the management system.

**Comment by Drenmi** [comment]
When I sign in, I get redirected to the root path (highpoint.herokuapp.com). This should be okay, right? As this is where our dashboard will be. 😀

**Comment by Drenmi** [comment]
Closing this for now. 😀
