### ISSUE TITLE
Error in donation edit form on donor page

### ISSUE THREAD

**Issue by limxinyuuu** [TechLadies/highpoint#40]
The donation edit form on the donor page currently shows multiple forms for all donations of the donor, rather than just one.

**Comment by Drenmi** [comment]
Good catch! This also reveals that our seed data is not that good. We should have donors with no donations, one donation, and many donations in our seed, so we can test all the edge cases.

**Comment by alahab2** [comment]
Also the donation/edit form doesn't let the User edit a date when the donation was made (`created_at`) which is needed if the donations are added post factum.

**Comment by Drenmi** [comment]
@alahab2: Ah. Let's create a separate issue for that. 😀
