### ISSUE TITLE
Create donation is not working

### ISSUE THREAD

**Issue by Drenmi** [TechLadies/highpoint#7]
Submitting a completed for to create a donation is not working at the moment.

This is because the `Donation` model doesn't accept nested attributes for `Donor`.

**Comment by limxinyuuu** [comment]
I have edited the Donation model to accept nested attributes for Donor.

**Comment by Drenmi** [comment]
@limxinyuuu: Awesome! When you create the PR, put "[Fix #7]" at the beginning. Then this issue will be referenced and close automatically when we merge the PR.
