### ISSUE TITLE
Can't run "rspec"

### ISSUE THREAD

**Issue by alahab2** [TechLadies/highpoint#91]
`rspec` gives following error:
```
...lib/code_climate/test_reporter.rb:60:in `logger': undefined method `configuration' for CodeClimate::TestReporter:Module (NoMethodError)
```

**Comment by alahab2** [comment]
`bundle exec rspec` is working fine, though.

**Comment by Drenmi** [comment]
You should always be running commands with `bundle exec`. This ensures that you're running with the version specified in the Gemfile. Running a "naked" command will use any version installed on your system.

**Comment by alahab2** [comment]
Opppps, didn't know. Removing the Issue then.
